### ISSUE TITLE
Keep StackView Transitions?

### ISSUE THREAD

**Issue by cibersheep** [ubports/qqc2-suru-style#11]
We have some default transitions when pages are pushed or popped from a StackView.

The rational behind it is that transitions should give a hint on what is happening when user taps on an element: if tap on the header of an email the transition should hint the user that that email is being `opened`.

Therefore, when an element of a list is tapped a page is enters «flying» from the right but it also does if we tap on the header icon for example. At then end, looks like the app is slower than it is as the header text (if) changes does it before than the page entering in.

My question is: Do we want to keep these transitions as default? Modify them? Delete them and implement this in another way?

**Comment by bhdouglass** [comment]
So I think there are two scenarios here, one where the page header is set on the window (fullcircle is an example of this) and one where the page header is set on the page. When it's set in the window the pages and the header update separately, when it's on the page they (should) come flying in together. We could solve this by recommending the page header be on the page rather than the window. So I think it becomes a question of if we want the transitions or not, or different transition.

**Comment by cibersheep** [comment]
That's true. TELEports does the header in the page flying.
Do we want «flying» transition? I was testing to take the flying and leaving only the fade in and I think it keeps the main Stefano idea a bit. I'll try to share a click

**Comment by bhdouglass** [comment]
Just a fade sounds fine to me. But does that have a similar problem for apps like full circle that have the header on the app and not the page?

**Comment by cibersheep** [comment]
If we only fade, I think is more subtle:
[devref.zip](https://github.com/ubports/qqc2-suru-style/files/2897345/devref.zip)

**Comment by bhdouglass** [comment]
That looks good and there isn't too much lag between the header and page updating.

**Comment by cibersheep** [comment]
I'll do a MR soon :)
