### ISSUE TITLE
Suru-styled Pages are missing background Rectangle

### ISSUE THREAD

**Issue by fredldotme** [ubports/qqc2-suru-style#20]
Since the removal of the background Rectangle (commit: bd803c9c2aed87894e5894ed5616c2de2d8c83c9)
the Page component differs from other styling implementations (Material, Universal) in that it allows see-through behavior, which might not be expected from an application coming from a different platform and using QQC2.
To keep friction low we might have to revert the commit that introduced this regression.

![screenshot20190330_123628363](https://user-images.githubusercontent.com/722660/55280109-5b29c100-5321-11e9-8dcc-362285bc490d.png)

**Comment by cibersheep** [comment]
Background Rectangle was deleted for several reasons:
 - uuitk expects to set the background color in the AppWindow. Any Page on top should take that color
 - performance issues: having a Rectangle in every Page additional to hits on performance
 - Page always take Suru.background{Light..Dark} depending on the theme, if you need to change the color, you have to add a Rectangle anyway

@bhdouglass do we have a workaround for this?

**Comment by bhdouglass** [comment]
@cibersheep rather than setting the background color on the application window, maybe we should look into doing something similar to the Material theme where they have the accent color that you can set. Actually, it might not make sense to set the background color like the old UITK does, but rather let users overwrite the background rectangles themselves (which might be the proper thing to do).

If its ok with you I think we should probably revert this change to keep with what other themes are doing: https://github.com/qt/qtquickcontrols2/blob/5.11/src/imports/controls/material/Page.qml#L56

**Comment by cibersheep** [comment]
Probably is a good idea to «break» with uuitk now that we do in other areas. Let's revert it then.

The way to change the background color is to replace all background Rectangles?

**Comment by bhdouglass** [comment]
I believe so
