### ISSUE TITLE
Add explanation on how to use it, build

### ISSUE THREAD

**Issue by lduboeuf** [ubports/qqc2-suru-style#28]

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qqc2-suru-style/-/issues/28

Sorry for your inconvenience.
