### ISSUE TITLE
Don't force dark style

### ISSUE THREAD

**Issue by bhdouglass** [ubports/qqc2-suru-style#31]
Once [ubuntu-ui-toolkit#39](https://github.com/ubports/ubuntu-ui-toolkit/issues/39) has been implemented Suru style should no longer force dark style on apps, but rather let them opt into using the dark style.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qqc2-suru-style/-/issues/31

Sorry for your inconvenience.
