### ISSUE TITLE
New spinner icon

### ISSUE THREAD

**Issue by mymike00** [ubports/qqc2-suru-style#4]
what about using a more dynamic spinner icon from canonical https://github.com/CanonicalLtd/desktop-design/blob/master/Toolkit%20%26%20Patterns/Theme/Progress/spinner.svg ?

**Comment by sverzegnassi** [comment]
That looks gorgeous! Well spotted, Michele!

It's something that could dramatically improve loading screens, however I would suggest to give it a low priority.

We can't use that SVG image as-is for a couple of reasons.

- QML doesn't support animated SVGs natively.
- That SVG from Canonical assumes that background is always white.

See screencast below. That circle is actually made by four different elements:

- An orange circle
- Three #FFFFFF shapes that are individually animated to give the appearance of one single elastic animation

![peek 16-05-2018 18-04](https://user-images.githubusercontent.com/1218443/40132062-0885a5f2-593c-11e8-8c6c-16bebf40045b.gif)

Since we don't make assumptions on the color of the window, we'd need to rewrite the animation using C++ and QSGNode, in order to apply a consistent transparency.

The good news though is that we might reuse some of the work done for the [Material style](http://code.qt.io/cgit/qt/qtquickcontrols2.git/tree/src/imports/controls/material/qquickmaterialbusyindicator.cpp).

In any case, the report is valid and any improvement on this area is welcome.

**Comment by mymike00** [comment]
yeah, I noticed the white shapes.
I'd like to help but I think I don't have the right skills for it...

**Comment by sverzegnassi** [comment]
Yes, `BusyIndicator` is tricky. It needs to keep spinning even if the main (GUI) thread is busy, that's why the animation is usually performed in the rendering thread. This can be achieved by using a QML [`Animator`](http://doc.qt.io/qt-5/qml-qtquick-animator.html).

However, I see now that [`Imagine` style](https://doc.qt.io/qt-5.10/qtquickcontrols2-imagine.html) from QtQuick Controls 2 5.10 uses animated `.webp` images for `BusyIndicator`.

Two things to investigate:

- If the Suru spinner would result in a reasonable sized `.webp` image (in `kb`);
- If there's a way to programmatically change the `.webp` spinner color according to the value of `Suru.highlightColor` property.

In case, that might definitely become an option for having more complex animations, without using over-engineered solutions.

For the time being, we can live with the current animation - which is still part of the Vanilla design specs.

**Comment by mymike00** [comment]
reported the issue https://github.com/CanonicalLtd/desktop-design/issues/112

**Comment by madsrh** [comment]
## Hi

This is a bit of a longshot, but I've worked on [some spinners](https://github.com/madsrh/yet-another-DMZ-cursor-theme) for the Ubuntu community theme and I was wondering if there's any chance that you could use that?
They are NOT vector, I only have the rendered png files 🤷‍♂️ but perhaps with [this tool](https://developers.google.com/speed/webp/docs/img2webp) to convert them to .webp

**Comment by mymike00** [comment]
yeah, we may have a look but only (as @sverzegnassi said)

> If there's a way to programmatically change the `.webp` spinner color according to the value of `Suru.highlightColor` property.

in that case, we can also take the spinner from canonical, render it in a sequence of images, change the color of the 3 little shapes from white to transparent and then make a `.webp`

**Comment by sverzegnassi** [comment]
@mymike00, even if I'm the original author of this project, I'm not involved anymore in any final decision for apps or toolkit. What I expressed here is just my personal opinion.

If someone can do that work, remove the white stripes and provide us the whole animation as a collection of high-res PNGs (i.e. 128x128 or 256x256 px), I'm sure the adoption of the new animation from Canonical would be much more easier. :)

If that's not possible, I'd let users to choose their preferred animation by running a survey within the community. (UBports marketing team likes this kind of things)

Thanks @madsrh for your posting. I like the "rainbow dots" animation, you've offered a number of very valuable options. Really appreciated!

**Comment by mymike00** [comment]
@madsrh Oh, I just saw you 3rd spinner is the same I suggested here...
How did you get those PNGs? is there a way to get bigger images?

**Comment by madsrh** [comment]
@mymike00 I used some evil proprietary software to create them 😉 Yes, I can render them larger.

**Comment by mymike00** [comment]
wow, thank you. but with proprietary you mean just closed source or you need to pay for it? can you give me its name?

**Comment by madsrh** [comment]
Sure, it's not a secret and I'm sure someone can do the same with Blender, but I use Adobe After Effects.

I've added 23 frames of 256x256px png files [here](https://github.com/madsrh/yet-another-DMZ-cursor-theme/tree/master/Communitheme_3/cursors/256x256)!

**Comment by mymike00** [comment]
I think you got confused and you rendered the unity spinner (number 2) instead of the Canonical spinner (number 3)

**Comment by madsrh** [comment]
> I think you got confused and you rendered the unity spinner (number 2) instead of the Canonical spinner (number 3)

Ahhhh, sorry! Yes, that was a bit too fast 🤦‍♂️  I'll look into it later

**Comment by madsrh** [comment]
@mymike00 I hope this works better 😄Grab [PNG's here](https://github.com/madsrh/yet-another-DMZ-cursor-theme/tree/master/Communitheme_3/cursors/256x256)

**Comment by mymike00** [comment]
@madsrh sorry but not yet... In the Canonical spinner, the 3 orange shapes change their length (take a look [here](https://github.com/CanonicalLtd/desktop-design/blob/master/Toolkit%20%26%20Patterns/Theme/Progress/spinner.svg)) and the 48x48 PNGs do it as well ([example](https://github.com/madsrh/yet-another-DMZ-cursor-theme/blob/master/Communitheme_3/cursors/48x48/watch_0033.png)) but that isn't done by the 256x256 ones...

**Comment by mymike00** [comment]
@madsrh ? have you read my message?

**Comment by madsrh** [comment]
@mymike00 Yes, but I haven't had much time to look into this.

I understand what you mean by having them rotate asynchronous. I have images for the correct animation now, but with white "holes" like the SVG spinner. Making them transparent is the hard part - I can't do that atm, but I will investigate again when I have more time.

**Comment by mymike00** [comment]
@madsrh well I can try to make them transparent if you can send me those frames.
Thanks!

**Comment by madsrh** [comment]
@mymike00 Okay, this seems to work now. Is [this](https://github.com/madsrh/yet-another-DMZ-cursor-theme/tree/master/Communitheme_2/cursors/256x256_transparent) correct? 😄

**Comment by mymike00** [comment]
Thank you very much @madsrh :exclamation: 
you definitely have to teach me :pray: :wink: 
I made some draft [here](https://github.com/mymike00/qqc2-suru-style/tree/master/qqc2-suru/assets/animated-spinner) but idk which one is the best: 34ms seems too fast while 35 is too slow...

**Comment by mymike00** [comment]
yeah, I notice that. [fixed](https://github.com/mymike00/qqc2-suru-style/blob/master/qqc2-suru/assets/animated-spinner/Canonical-Design_34_thin.gif) :stuck_out_tongue_winking_eye: 
now the last thing to fix I think is to add anti aliasing and we'll reach perfection :+1:

**Comment by mymike00** [comment]
@sverzegnassi I made also a [webp](https://github.com/mymike00/qqc2-suru-style/blob/master/qqc2-suru/assets/animated-spinner/Canonical-Design_34_thin.webp) version, it's about 30kB
ah, should we make it blue instead of orange?

**Comment by bhdouglass** [comment]
Thanks for the interest in this guys, but I believe we should just keep this simple for now.
