### ISSUE TITLE
What dose .qmake.conf do?

### ISSUE THREAD

**Issue by MohsenNz** [ubports/qqc2-suru-style#42]
Hi, I'm working on my fork of qqc2-suru-style. I need to know how .qmake.conf file work. can u help me ? thank you.

**Comment by bhdouglass** [comment]
As far as I can tell it configures specific things in qmake

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qqc2-suru-style/-/issues/42

Sorry for your inconvenience.
