### ISSUE TITLE
Move to cmake?

### ISSUE THREAD

**Issue by mariogrip** [ubports/qqc2-suru-style#51]
Since qmake is both hard to work with and semi deprecated upstream. 

Also most of our components use cmake, and i'm planing to move more of them over.

**Comment by bhdouglass** [comment]
I am totally on board with this :+1:

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qqc2-suru-style/-/issues/51

Sorry for your inconvenience.
