### ISSUE TITLE
Dialogs expose old window buffers during redraws

### ISSUE THREAD

**Issue by fredldotme** [ubports/qqc2-suru-style#55]
Steps to reproduce:
- Open GhostCloud from the OpenStore
- Press the hamburger menu 
- Select "About GhostCloud"

Expectation:
- Scrolling through the page should feel fluid

Actual result:
- Old window buffers are kept and shown during redraw when scrolling the page

**Comment by dobey** [comment]
This seems to behave properly on my Nexus 4.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/qqc2-suru-style/-/issues/55

Sorry for your inconvenience.
